version: "3.9"
services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./src:/app
      - nuxt_node_modules:/app/node_modules
    ports:
      - 80:3000
    tty: true

volumes:
  nuxt_node_modules:
